### ISSUE TITLE
Delete Image

### ISSUE THREAD

**Issue by ptevis42** [AppFolioOnboarding/image-sharer-dannycho7#8]
#### As a user I want to delete an image.

__Story__:

Our users are awesome at adding images to our web service. Some of our users
add dozens in a single session. Occasionally, however, some users add the wrong
image, and would like a way to remove those images. Please provide our users
with the ability to delete images. Note that at this point we trust our users
not to abuse this feature and delete more images than they should.

__Acceptance criteria__:
- [x] The user is prompted for confirmation prior to deletion.
- [x] Deleted images are removed from the homepage.

__Dependencies__:
- Image Index

**Comment by dannycho7** [comment]
This was solved in a prior merge (Issue #7)
